Feature/eco 574/eco 2339 implementation phase 2
spryker-eco/after-pay pull request #12
Opened 2019-01-18 14:54 UTC by IvanovRuslanSpryker

2019-01-21 18:00 UTC, alex-galych commented on src/SprykerEco/Zed/AfterPay/Business/AfterPayBusinessFactory.php
> +        switch ($authorizeWorkflow) {
We are not using switch statement.

2019-01-21 18:01 UTC, alex-galych commented on src/SprykerEco/Zed/AfterPay/Business/Payment/Filter/TwoStepAuthorizePaymentMethodsFilter.php
> +            if($this->isPaymentProviderAfterPay($paymentMethodTransfer) &&
Please move conditions to separate method, they have to be clear and easy to understand.

2019-01-31 09:42 UTC, SerhiiBabich requested changes
You already have by architecture sniffer: 33 errors
You can find them here: https://travis-ci.org/spryker-eco/after-pay/builds/486346640

2019-01-31 09:58 UTC, alex-galych commented on src/SprykerEco/Zed/AfterPay/Business/Payment/Filter/TwoStepAuthorizePaymentMethodsFilter.php
> +        if ($this->isPaymentProviderAfterPay($paymentMethodTransfer) &&
Please move condition to another method, it's too complicated

2019-01-31 10:11 UTC, SergeBabich commented on src/SprykerEco/Zed/AfterPay/Business/Payment/Filter/TwoStepAuthorizePaymentMethodsFilter.php
> +        return true;
I think you can do here like:
```
{
    return $this->isPaymentProviderAfterPay($paymentMethodTransfer) === false && 
        $this->isAvailable($paymentMethodTransfer, $quoteTransfer->getAfterPayAvailablePaymentMethods()) !== false
}
```

2019-01-31 10:12 UTC, SergeBabich commented on src/SprykerEco/Zed/AfterPay/Business/Order/Saver.php
> +        if ($quoteTransfer->getAfterPayAvailablePaymentMethods()) {
it would be nice to change it to: $quoteTransfer->getAfterPayAvailablePaymentMethods() !== null

2019-01-31 10:30 UTC, SerhiiBabich requested changes

2019-01-31 10:30 UTC, SerhiiBabich commented on src/SprykerEco/Zed/AfterPay/Business/Payment/Mapper/QuoteToRequestTransfer.php
> +    protected function getImageUrlFromOrderItem(ItemTransfer $itemTransfer): string
This method should always return string, but in case when `$itemTransfer->getImages()` will `null` it would be exception here, please, check it

2019-01-31 10:30 UTC, SerhiiBabich commented on src/SprykerEco/Zed/AfterPay/Business/Payment/Mapper/QuoteToRequestTransfer.php
> +        $hasImageHttpProtocolInUrl = strpos($url, 'http:') || strpos($url, 'https:');
`(0 || false)` alway will `FALSE`

2019-01-31 10:30 UTC, SerhiiBabich commented on src/SprykerEco/Zed/AfterPay/Business/Payment/Mapper/QuoteToRequestTransfer.php
> +        $item = (new AfterPayRequestOrderItemTransfer())
please, do return here, we don't `$item` var at all

2019-01-31 10:30 UTC, SerhiiBabich commented on src/SprykerEco/Zed/AfterPay/Business/Payment/Transaction/Handler/CaptureTransactionHandler.php
> +        if ($paymentTransfer->getExpenseTotal()) {
You know that getExpenseTotal() could be null, so it would be nice to do:
`if ($paymentTransfer->getExpenseTotal() !== null) {`

2019-01-31 10:30 UTC, SerhiiBabich commented on src/SprykerEco/Zed/AfterPay/Business/Payment/Transaction/Handler/RefundTransactionHandler.php
> +        if ($paymentTransfer->getExpenseTotal()) {
You know that getExpenseTotal() could be null, so it would be nice to do:
`if ($paymentTransfer-> getExpenseTotal() !== null) {`

2019-01-31 10:30 UTC, SerhiiBabich commented on tests/SprykerEcoTest/Zed/AfterPay/codeception.yml
> +                - \SprykerTest\Shared\Testify\Helper\ConfigHelper
we need to add empty line at the end of file

2019-01-31 15:53 UTC, alex-galych approved these changes

2019-01-31 15:53 UTC, merged