[ECO-574] Arvato - AfterPay
spryker-eco/after-pay pull request #13
Opened 2019-01-31 17:34 UTC by IvanovRuslanSpryker

- Developer(s): @IvanovRuslanSpryker

- Ticket: https://spryker.atlassian.net/browse/ECO-574

- Documentation: https://spryker.atlassian.net/wiki/spaces/ECO/pages/788071193/Afterpay+Documentation

#### Please confirm

- [ ] No new OS components - or they have been approved by legal department

#### Documentation

- [ ] Functional documentation provided or in progress?
- [ ] Integration guide for projects provided or not needed?
- [ ] Migration guides for all contained majors provided or not needed?

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   AfterPay              | major (new)           |                       |

#### Release Notes

Added integration functionality for AfterPay.

-----------------------------------------

#### Module AfterPay

##### Change log

Initial Release

* Next payment methods have been added:
** Invoice;
* Added two checkout process:
** One-Step Authorization → AFTERPAY_AUTHORIZE_WORKFLOW_ONE_STEP;
** Two-Step Authorization → AFTERPAY_AUTHORIZE_WORKFLOW_TWO_STEPS;
* Added functional tests.

2019-02-01 13:55 UTC, alex-galych approved these changes
Reviewed in internal reviews.

2019-02-01 15:12 UTC, lockw1n requested changes

2019-02-01 15:12 UTC, lockw1n commented on .travis.yml
> +  - ./ecoci/build/travis.sh
Please add new line at the of the file.

2019-02-01 15:12 UTC, lockw1n commented on phpstan.neon
>  services:
This section has to be removed with all its items.

2019-02-01 15:12 UTC, lockw1n commented on src/SprykerEco/Yves/AfterPay/Form/DataProvider/InvoiceDataProvider.php
> +        if ($quoteTransfer->getPayment() === null) {
We prefer early return.

2019-02-01 15:12 UTC, lockw1n commented on src/SprykerEco/Zed/AfterPay/AfterPayConfig.php
> +        switch ($paymentMethod) {
This switch does not have any sense. And also business logic should not be present in config class.

2019-02-01 15:12 UTC, lockw1n commented on src/SprykerEco/Zed/AfterPay/Business/AdditionalServices/Handler/LookupCustomerHandler.php
> +class LookupCustomerHandler implements LookupCustomerHandlerInterface
In general we have accepted RFC that we disallow handlers. But you don't need to fix it right now. You can create a task into technical debts and keep in mind in further integrations.

2019-02-01 15:12 UTC, lockw1n commented on src/SprykerEco/Zed/AfterPay/Business/AfterPayBusinessFactory.php
> + * @method \SprykerEco\Zed\AfterPay\Persistence\AfterPayQueryContainerInterface getQueryContainer()
QueryContainers should not be used. Please also put it into technical debts.

2019-02-01 15:12 UTC, lockw1n commented on src/SprykerEco/Zed/AfterPay/Business/Api/Adapter/AfterPayApiAdapter.php
> +            ->adapterFactory
I would prefer to move it on previous line
```
return $this->adapterFactory
    ->createAvailablePaymentMethodsCall()
    ->execute($requestTransfer);
```

Please change methods in this file.

2019-02-01 15:12 UTC, lockw1n commented on src/SprykerEco/Zed/AfterPay/Business/Api/Adapter/ApiCall/AuthorizePaymentCall.php
> +        $responseTransfer
You can merge it with transfer creation.
```
$responseTransfer = (new AfterPayApiResponseTransfer())
    ->set()
    ->set();
```

2019-02-01 15:12 UTC, lockw1n commented on src/SprykerEco/Zed/AfterPay/Business/Api/Adapter/ApiCall/AvailablePaymentMethodsCall.php
> +        $responseTransfer
Same. Please merge it with transfer creation.

2019-02-01 15:12 UTC, lockw1n commented on src/SprykerEco/Zed/AfterPay/Business/Api/Adapter/ApiCall/LookupCustomerCall.php
> +        $userProfileTransfer
Please merge it with transfer creation.

2019-02-01 15:12 UTC, lockw1n commented on src/SprykerEco/Zed/AfterPay/Business/Api/Adapter/ApiCall/LookupCustomerCall.php
> +        $lookupAddressTransfer
Same please.

2019-02-01 15:12 UTC, lockw1n commented on src/SprykerEco/Zed/AfterPay/Business/Payment/Mapper/OrderToRequestTransfer.php
> +    protected static $paymentMethods = [
Would be nice to move it to constant.

2019-02-01 15:12 UTC, lockw1n commented on src/SprykerEco/Zed/AfterPay/Business/Payment/Mapper/QuoteToRequestTransfer.php
> +        $customerRequestTransfer
Please merge it with transfer creation.

2019-02-01 15:12 UTC, lockw1n commented on src/SprykerEco/Zed/AfterPay/Business/Payment/Mapper/QuoteToRequestTransfer.php
> +        $orderItemRequestTransfer
Same. Merge it please.

2019-02-01 15:12 UTC, lockw1n commented on src/SprykerEco/Zed/AfterPay/Business/Payment/Mapper/QuoteToRequestTransfer.php
> +        $customerAddressRequestTransfer
Same.

2019-02-01 15:12 UTC, lockw1n commented on src/SprykerEco/Zed/AfterPay/Business/Payment/PaymentReader.php
> +    public function getPaymentByIdSalesOrder(int $idSalesOrder): AfterPayPaymentTransfer
The name of methods like this should be `findPayment...()`. Put it to technical debts.

2019-02-01 15:12 UTC, lockw1n commented on src/SprykerEco/Zed/AfterPay/Business/Payment/PaymentWriter.php
> +    public function setIdReservationByIdSalesOrder(string $idReservation, int $idSalesOrder): void
The name of methods like this should be `savePayment...()`. Put it to technical debts.

2019-02-01 15:12 UTC, lockw1n commented on src/SprykerEco/Zed/AfterPay/Business/Payment/PaymentWriter.php
> +            ->save();
This should be through entityManager. Put it to technical debts.

2019-02-01 15:12 UTC, aleksey-kotsuba commented on src/SprykerEco/Zed/AfterPay/Communication/Plugin/Oms/Command/AuthorizePlugin.php
> +class AuthorizePlugin extends AbstractPlugin implements CommandByOrderInterface
In general we do not allow logic in plugins. Pease put it into technical debts.

2019-02-01 16:31 UTC, IvanovRuslanSpryker commented on src/SprykerEco/Zed/AfterPay/Business/Payment/Mapper/OrderToRequestTransfer.php
> +    protected static $paymentMethods = [
I'm not sure.

2019-02-01 16:32 UTC, IvanovRuslanSpryker commented on phpstan.neon
>  services:
Please clarify.

2019-02-07 09:15 UTC, lockw1n approved these changes

2019-02-07 10:17 UTC, merged