Release 1.0.4
spryker-eco/after-pay pull request #20
Opened 2019-06-19 13:53 UTC by vhrychenko

- Developer(s): @vhrychenko

- Ticket: https://spryker.atlassian.net/browse/ECO-2707

#### Please confirm

- [ ] No new OS components - or they have been approved by legal department

#### Documentation

- [ ] Functional documentation provided or in progress?
- [ ] Integration guide for projects provided or not needed?
- [ ] Migration guides for all contained majors provided or not needed?

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   AfterPay              | patch                 | AfterPay              |

#### Release Notes

Fixed argument type mismatch if a reservation was not successful

-----------------------------------------

#### Module AfterPay

##### Change log

Bugfixes

- Adjusted `PaymentAuthorizeWriter::save()` so it might get null parameters in case a reservation was not successful

2019-06-19 14:03 UTC, gechetspr requested changes
Please specify in change logs, that param order for method was changed

2019-06-19 14:03 UTC, gechetspr commented on src/SprykerEco/Zed/AfterPay/Business/Payment/PaymentWriter.php
> +    public function setIdReservationByIdSalesOrder(int $idSalesOrder, string $idReservation = null): void
`$idReservation` is nullable

2019-06-19 14:03 UTC, gechetspr commented on src/SprykerEco/Zed/AfterPay/Business/Payment/PaymentWriterInterface.php
> +    public function setIdReservationByIdSalesOrder(int $idSalesOrder, string $idReservation = null): void;
same

2019-06-19 14:03 UTC, gechetspr commented on src/SprykerEco/Zed/AfterPay/Business/Payment/Transaction/Authorize/PaymentAuthorizeWriter.php
> +    public function save(string $orderReference, string $idReservation = null, string $idCheckout = null): void
same

2019-06-19 14:03 UTC, gechetspr commented on src/SprykerEco/Zed/AfterPay/Business/Payment/Transaction/Authorize/PaymentAuthorizeWriterInterface.php
> +    public function save(string $orderReference, string $idReservation = null, string $idCheckout = null): void;
same

2019-06-19 14:16 UTC, gechetspr approved these changes

2019-07-01 12:30 UTC, alex-galych commented on tests/_data/after-pay.databuilder.xml
> +        <property name="unitGrossPrice" dataBuilderRule="randomFloat(2)"  />
This should be fixed

2019-07-01 12:34 UTC, alex-galych approved these changes

2019-07-01 12:39 UTC, merged